// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message describing Instance object
public struct Instance: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. name of resource
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The state of the VM.
  public var state: Instance.State = Instance.State()

  /// Output only. The location of the VM.
  public var region: Swift.String = Swift.String()

  /// Output only. Map with Product_Name and Activation State of the VM.
  public var productActivation: [Swift.String: ActivationState] = [:]

  /// Output only. license version id.
  public var licenseVersionId: Swift.String = Swift.String()

  /// Required. Compute Instance resource name, i.e.
  /// projects/{project}/zones/{zone}/instances/{instance}
  public var computeInstance: Swift.String = Swift.String()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// VM status enum.
  public enum State: Codable, Equatable, Sendable {
    /// The Status of the VM is unspecified.
    case unspecified
    /// Resources are being allocated for the instance.
    case provisioning
    /// All required resources have been allocated and
    /// the instance is being started.
    case staging
    /// The instance is running.
    case running
    /// The instance is currently stopping (either being deleted or terminated).
    case stopping
    /// The instance has stopped due to various reasons (user request, VM
    /// preemption, project freezing, etc.).
    case stopped
    /// The instance has failed in some way.
    case terminated
    /// The instance is in repair.
    case repairing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .staging: return 2
      case .running: return 3
      case .stopping: return 4
      case .stopped: return 5
      case .terminated: return 6
      case .repairing: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .staging: return "STAGING"
      case .running: return "RUNNING"
      case .stopping: return "STOPPING"
      case .stopped: return "STOPPED"
      case .terminated: return "TERMINATED"
      case .repairing: return "REPAIRING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "STAGING": self = .staging
      case "RUNNING": self = .running
      case "STOPPING": self = .stopping
      case "STOPPED": self = .stopped
      case "TERMINATED": self = .terminated
      case "REPAIRING": self = .repairing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .staging
      case 3: self = .running
      case 4: self = .stopping
      case 5: self = .stopped
      case 6: self = .terminated
      case 7: self = .repairing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .provisioning: return try container.encode(1)
      case .staging: return try container.encode(2)
      case .running: return try container.encode(3)
      case .stopping: return try container.encode(4)
      case .stopped: return try container.encode(5)
      case .terminated: return try container.encode(6)
      case .repairing: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.licensemanager.v1.Instance"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
