// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol LicenseManagerStub: Sendable {
    func listConfigurations(
      request: ListConfigurationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse

    func getConfiguration(
      request: GetConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Configuration

    func createConfiguration(
      request: CreateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateConfiguration(
      request: UpdateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteConfiguration(
      request: DeleteConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListInstancesResponse

    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Instance

    func deactivateConfiguration(
      request: DeactivateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func reactivateConfiguration(
      request: ReactivateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func queryConfigurationLicenseUsage(
      request: QueryConfigurationLicenseUsageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse

    func aggregateUsage(
      request: AggregateUsageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.AggregateUsageResponse

    func listProducts(
      request: ListProductsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListProductsResponse

    func getProduct(
      request: GetProductRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Product

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
