// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Service describing handlers for resources
///
/// @Snippet(path: "LicenseManagerQuickstart")
public final class LicenseManagerClient: Clients.LicenseManagerProtocol, Sendable {
  let inner: any Clients.LicenseManagerStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `LicenseManagerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.LicenseManagerStub = try Clients.LicenseManagerTransport(options)
    inner = Clients.LicenseManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.LicenseManagerLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Configurations in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListConfigurations")
  public func listConfigurations(
    request: ListConfigurationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse {
    try await self.inner.listConfigurations(request: request, options: options)
  }

  /// Lists Configurations in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListConfigurations")
  public func listConfigurations(
    byItem: ListConfigurationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Configuration, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listConfigurations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Configuration.
  ///
  /// @Snippet(path: "LicenseManager_GetConfiguration")
  public func getConfiguration(
    request: GetConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Configuration {
    try await self.inner.getConfiguration(request: request, options: options)
  }

  /// Creates a new Configuration in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_CreateConfiguration")
  public func createConfiguration(
    request: CreateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createConfiguration(request: request, options: options)
  }

  /// Creates a new Configuration in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_CreateConfiguration")
  public func createConfiguration(
    withPolling: CreateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      return try op._extractStatus(Configuration.self)
    }
    let rawOp = try await self.createConfiguration(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single Configuration.
  ///
  /// @Snippet(path: "LicenseManager_UpdateConfiguration")
  public func updateConfiguration(
    request: UpdateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateConfiguration(request: request, options: options)
  }

  /// Updates the parameters of a single Configuration.
  ///
  /// @Snippet(path: "LicenseManager_UpdateConfiguration")
  public func updateConfiguration(
    withPolling: UpdateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      return try op._extractStatus(Configuration.self)
    }
    let rawOp = try await self.updateConfiguration(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Configuration.
  ///
  /// @Snippet(path: "LicenseManager_DeleteConfiguration")
  public func deleteConfiguration(
    request: DeleteConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteConfiguration(request: request, options: options)
  }

  /// Deletes a single Configuration.
  ///
  /// @Snippet(path: "LicenseManager_DeleteConfiguration")
  public func deleteConfiguration(
    withPolling: DeleteConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteConfiguration(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Instances in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListInstances")
  public func listInstances(
    request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListInstancesResponse {
    try await self.inner.listInstances(request: request, options: options)
  }

  /// Lists Instances in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListInstances")
  public func listInstances(
    byItem: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLicenseManagerV1.ListInstancesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listInstances(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Instance.
  ///
  /// @Snippet(path: "LicenseManager_GetInstance")
  public func getInstance(
    request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Instance {
    try await self.inner.getInstance(request: request, options: options)
  }

  /// Deactivates the given configuration.
  ///
  /// @Snippet(path: "LicenseManager_DeactivateConfiguration")
  public func deactivateConfiguration(
    request: DeactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deactivateConfiguration(request: request, options: options)
  }

  /// Deactivates the given configuration.
  ///
  /// @Snippet(path: "LicenseManager_DeactivateConfiguration")
  public func deactivateConfiguration(
    withPolling: DeactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      return try op._extractStatus(Configuration.self)
    }
    let rawOp = try await self.deactivateConfiguration(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Reactivates the given configuration.
  ///
  /// @Snippet(path: "LicenseManager_ReactivateConfiguration")
  public func reactivateConfiguration(
    request: ReactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.reactivateConfiguration(request: request, options: options)
  }

  /// Reactivates the given configuration.
  ///
  /// @Snippet(path: "LicenseManager_ReactivateConfiguration")
  public func reactivateConfiguration(
    withPolling: ReactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      return try op._extractStatus(Configuration.self)
    }
    let rawOp = try await self.reactivateConfiguration(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// License Usage information for a Configuration.
  ///
  /// @Snippet(path: "LicenseManager_QueryConfigurationLicenseUsage")
  public func queryConfigurationLicenseUsage(
    request: QueryConfigurationLicenseUsageRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse {
    try await self.inner.queryConfigurationLicenseUsage(request: request, options: options)
  }

  /// Aggregates Usage per Instance for a Configuration.
  ///
  /// @Snippet(path: "LicenseManager_AggregateUsage")
  public func aggregateUsage(
    request: AggregateUsageRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.AggregateUsageResponse {
    try await self.inner.aggregateUsage(request: request, options: options)
  }

  /// Aggregates Usage per Instance for a Configuration.
  ///
  /// @Snippet(path: "LicenseManager_AggregateUsage")
  public func aggregateUsage(
    byItem: AggregateUsageRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Usage, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLicenseManagerV1.AggregateUsageResponse in
      var request = byItem
      request.pageToken = token
      return try await self.aggregateUsage(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists Products in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListProducts")
  public func listProducts(
    request: ListProductsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListProductsResponse {
    try await self.inner.listProducts(request: request, options: options)
  }

  /// Lists Products in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListProducts")
  public func listProducts(
    byItem: ListProductsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLicenseManagerV1.ListProductsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listProducts(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Product.
  ///
  /// @Snippet(path: "LicenseManager_GetProduct")
  public func getProduct(
    request: GetProductRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Product {
    try await self.inner.getProduct(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "LicenseManager_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "LicenseManager_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "LicenseManager_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "LicenseManager_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "LicenseManager_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "LicenseManager_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "LicenseManager_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "LicenseManager_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `LicenseManagerClient`.
  ///
  /// To mock `LicenseManagerClient` change your functions to receive
  /// `some LicenseManagerProtocol` or `any LicenseManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol LicenseManagerProtocol {
    /// See `LicenseManagerClient.listConfigurations`.
    func listConfigurations(request: ListConfigurationsRequest) async throws
      -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse

    /// See `LicenseManagerClient.listConfigurations`.
    func listConfigurations(
      byItem: ListConfigurationsRequest
    ) throws -> any AsyncSequence<Configuration, Swift.Error>

    /// See `LicenseManagerClient.listConfigurations`.
    func listConfigurations(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Configuration, Swift.Error>

    /// See `LicenseManagerClient.getConfiguration`.
    func getConfiguration(request: GetConfigurationRequest) async throws
      -> GoogleCloudLicenseManagerV1.Configuration

    /// See `LicenseManagerClient.getConfiguration`.
    func getConfiguration(
      name: Swift.String,
    ) async throws -> GoogleCloudLicenseManagerV1.Configuration

    /// See `LicenseManagerClient.createConfiguration`.
    func createConfiguration(request: CreateConfigurationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.createConfiguration`.
    func createConfiguration(withPolling: CreateConfigurationRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.createConfiguration`.
    func createConfiguration(
      parent: Swift.String,
      configuration: Configuration?,
      configurationId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.updateConfiguration`.
    func updateConfiguration(request: UpdateConfigurationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.updateConfiguration`.
    func updateConfiguration(withPolling: UpdateConfigurationRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.updateConfiguration`.
    func updateConfiguration(
      configuration: Configuration?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.deleteConfiguration`.
    func deleteConfiguration(request: DeleteConfigurationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.deleteConfiguration`.
    func deleteConfiguration(withPolling: DeleteConfigurationRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `LicenseManagerClient.deleteConfiguration`.
    func deleteConfiguration(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `LicenseManagerClient.listInstances`.
    func listInstances(request: ListInstancesRequest) async throws
      -> GoogleCloudLicenseManagerV1.ListInstancesResponse

    /// See `LicenseManagerClient.listInstances`.
    func listInstances(
      byItem: ListInstancesRequest
    ) throws -> any AsyncSequence<Instance, Swift.Error>

    /// See `LicenseManagerClient.listInstances`.
    func listInstances(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Instance, Swift.Error>

    /// See `LicenseManagerClient.getInstance`.
    func getInstance(request: GetInstanceRequest) async throws
      -> GoogleCloudLicenseManagerV1.Instance

    /// See `LicenseManagerClient.getInstance`.
    func getInstance(
      name: Swift.String,
    ) async throws -> GoogleCloudLicenseManagerV1.Instance

    /// See `LicenseManagerClient.deactivateConfiguration`.
    func deactivateConfiguration(request: DeactivateConfigurationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.deactivateConfiguration`.
    func deactivateConfiguration(withPolling: DeactivateConfigurationRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.deactivateConfiguration`.
    func deactivateConfiguration(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.reactivateConfiguration`.
    func reactivateConfiguration(request: ReactivateConfigurationRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.reactivateConfiguration`.
    func reactivateConfiguration(withPolling: ReactivateConfigurationRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.reactivateConfiguration`.
    func reactivateConfiguration(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.queryConfigurationLicenseUsage`.
    func queryConfigurationLicenseUsage(request: QueryConfigurationLicenseUsageRequest) async throws
      -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse

    /// See `LicenseManagerClient.queryConfigurationLicenseUsage`.
    func queryConfigurationLicenseUsage(
      name: Swift.String,
      startTime: GoogleCloudWKT.Timestamp?,
      endTime: GoogleCloudWKT.Timestamp?,
    ) async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse

    /// See `LicenseManagerClient.aggregateUsage`.
    func aggregateUsage(request: AggregateUsageRequest) async throws
      -> GoogleCloudLicenseManagerV1.AggregateUsageResponse

    /// See `LicenseManagerClient.aggregateUsage`.
    func aggregateUsage(
      byItem: AggregateUsageRequest
    ) throws -> any AsyncSequence<Usage, Swift.Error>

    /// See `LicenseManagerClient.aggregateUsage`.
    func aggregateUsage(
      name: Swift.String,
      startTime: GoogleCloudWKT.Timestamp?,
      endTime: GoogleCloudWKT.Timestamp?,
    ) throws -> any AsyncSequence<Usage, Swift.Error>

    /// See `LicenseManagerClient.listProducts`.
    func listProducts(request: ListProductsRequest) async throws
      -> GoogleCloudLicenseManagerV1.ListProductsResponse

    /// See `LicenseManagerClient.listProducts`.
    func listProducts(
      byItem: ListProductsRequest
    ) throws -> any AsyncSequence<Product, Swift.Error>

    /// See `LicenseManagerClient.listProducts`.
    func listProducts(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Product, Swift.Error>

    /// See `LicenseManagerClient.getProduct`.
    func getProduct(request: GetProductRequest) async throws -> GoogleCloudLicenseManagerV1.Product

    /// See `LicenseManagerClient.getProduct`.
    func getProduct(
      name: Swift.String,
    ) async throws -> GoogleCloudLicenseManagerV1.Product

    /// See `LicenseManagerClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `LicenseManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `LicenseManagerClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `LicenseManagerClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `LicenseManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `LicenseManagerClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `LicenseManagerClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `LicenseManagerClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `LicenseManagerClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `LicenseManagerClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `LicenseManagerClient.listConfigurations`.
    func listConfigurations(
      request: ListConfigurationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse

    /// See `LicenseManagerClient.listConfigurations`.
    func listConfigurations(
      byItem: ListConfigurationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Configuration, Swift.Error>

    /// See `LicenseManagerClient.getConfiguration`.
    func getConfiguration(
      request: GetConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Configuration

    /// See `LicenseManagerClient.createConfiguration`.
    func createConfiguration(
      request: CreateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.createConfiguration`.
    func createConfiguration(
      withPolling: CreateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.updateConfiguration`.
    func updateConfiguration(
      request: UpdateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.updateConfiguration`.
    func updateConfiguration(
      withPolling: UpdateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.deleteConfiguration`.
    func deleteConfiguration(
      request: DeleteConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.deleteConfiguration`.
    func deleteConfiguration(
      withPolling: DeleteConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `LicenseManagerClient.listInstances`.
    func listInstances(
      request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListInstancesResponse

    /// See `LicenseManagerClient.listInstances`.
    func listInstances(
      byItem: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Instance, Swift.Error>

    /// See `LicenseManagerClient.getInstance`.
    func getInstance(
      request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Instance

    /// See `LicenseManagerClient.deactivateConfiguration`.
    func deactivateConfiguration(
      request: DeactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.deactivateConfiguration`.
    func deactivateConfiguration(
      withPolling: DeactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.reactivateConfiguration`.
    func reactivateConfiguration(
      request: ReactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.reactivateConfiguration`.
    func reactivateConfiguration(
      withPolling: ReactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.queryConfigurationLicenseUsage`.
    func queryConfigurationLicenseUsage(
      request: QueryConfigurationLicenseUsageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse

    /// See `LicenseManagerClient.aggregateUsage`.
    func aggregateUsage(
      request: AggregateUsageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.AggregateUsageResponse

    /// See `LicenseManagerClient.aggregateUsage`.
    func aggregateUsage(
      byItem: AggregateUsageRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Usage, Swift.Error>

    /// See `LicenseManagerClient.listProducts`.
    func listProducts(
      request: ListProductsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListProductsResponse

    /// See `LicenseManagerClient.listProducts`.
    func listProducts(
      byItem: ListProductsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Product, Swift.Error>

    /// See `LicenseManagerClient.getProduct`.
    func getProduct(
      request: GetProductRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Product

    /// See `LicenseManagerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `LicenseManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `LicenseManagerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `LicenseManagerClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `LicenseManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `LicenseManagerClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `LicenseManagerClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.LicenseManagerProtocol {
  public func listConfigurations(request: ListConfigurationsRequest) async throws
    -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse
  {
    try await self.listConfigurations(request: request, options: .init())
  }

  public func listConfigurations(
    request: ListConfigurationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listConfigurations(
    byItem: ListConfigurationsRequest
  ) throws -> any AsyncSequence<Configuration, Swift.Error> {
    try self.listConfigurations(byItem: byItem, options: .init())
  }

  public func listConfigurations(
    byItem: ListConfigurationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Configuration, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listConfigurations(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Configuration, Swift.Error> {
    let request = ListConfigurationsRequest().with {
      $0.parent = parent
    }
    return try self.listConfigurations(byItem: request)
  }

  public func getConfiguration(request: GetConfigurationRequest) async throws
    -> GoogleCloudLicenseManagerV1.Configuration
  {
    try await self.getConfiguration(request: request, options: .init())
  }

  public func getConfiguration(
    request: GetConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Configuration {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getConfiguration(
    name: Swift.String,
  ) async throws -> GoogleCloudLicenseManagerV1.Configuration {
    let request = GetConfigurationRequest().with {
      $0.name = name
    }
    return try await self.getConfiguration(request: request)
  }

  public func createConfiguration(request: CreateConfigurationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createConfiguration(request: request, options: .init())
  }

  public func createConfiguration(
    request: CreateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createConfiguration(withPolling: CreateConfigurationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Configuration>
  {
    try await self.createConfiguration(withPolling: withPolling, options: .init())
  }

  public func createConfiguration(
    withPolling: CreateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createConfiguration(
    parent: Swift.String,
    configuration: Configuration?,
    configurationId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let request = CreateConfigurationRequest().with {
      $0.parent = parent
      $0.configuration = configuration
      $0.configurationId = configurationId
    }
    return try await self.createConfiguration(withPolling: request)
  }

  public func updateConfiguration(request: UpdateConfigurationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateConfiguration(request: request, options: .init())
  }

  public func updateConfiguration(
    request: UpdateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateConfiguration(withPolling: UpdateConfigurationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Configuration>
  {
    try await self.updateConfiguration(withPolling: withPolling, options: .init())
  }

  public func updateConfiguration(
    withPolling: UpdateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateConfiguration(
    configuration: Configuration?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let request = UpdateConfigurationRequest().with {
      $0.configuration = configuration
      $0.updateMask = updateMask
    }
    return try await self.updateConfiguration(withPolling: request)
  }

  public func deleteConfiguration(request: DeleteConfigurationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteConfiguration(request: request, options: .init())
  }

  public func deleteConfiguration(
    request: DeleteConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteConfiguration(withPolling: DeleteConfigurationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteConfiguration(withPolling: withPolling, options: .init())
  }

  public func deleteConfiguration(
    withPolling: DeleteConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteConfiguration(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteConfigurationRequest().with {
      $0.name = name
    }
    return try await self.deleteConfiguration(withPolling: request)
  }

  public func listInstances(request: ListInstancesRequest) async throws
    -> GoogleCloudLicenseManagerV1.ListInstancesResponse
  {
    try await self.listInstances(request: request, options: .init())
  }

  public func listInstances(
    request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListInstancesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listInstances(
    byItem: ListInstancesRequest
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    try self.listInstances(byItem: byItem, options: .init())
  }

  public func listInstances(
    byItem: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLicenseManagerV1.ListInstancesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInstances(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    let request = ListInstancesRequest().with {
      $0.parent = parent
    }
    return try self.listInstances(byItem: request)
  }

  public func getInstance(request: GetInstanceRequest) async throws
    -> GoogleCloudLicenseManagerV1.Instance
  {
    try await self.getInstance(request: request, options: .init())
  }

  public func getInstance(
    request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Instance {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getInstance(
    name: Swift.String,
  ) async throws -> GoogleCloudLicenseManagerV1.Instance {
    let request = GetInstanceRequest().with {
      $0.name = name
    }
    return try await self.getInstance(request: request)
  }

  public func deactivateConfiguration(request: DeactivateConfigurationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deactivateConfiguration(request: request, options: .init())
  }

  public func deactivateConfiguration(
    request: DeactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deactivateConfiguration(withPolling: DeactivateConfigurationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Configuration>
  {
    try await self.deactivateConfiguration(withPolling: withPolling, options: .init())
  }

  public func deactivateConfiguration(
    withPolling: DeactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deactivateConfiguration(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let request = DeactivateConfigurationRequest().with {
      $0.name = name
    }
    return try await self.deactivateConfiguration(withPolling: request)
  }

  public func reactivateConfiguration(request: ReactivateConfigurationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.reactivateConfiguration(request: request, options: .init())
  }

  public func reactivateConfiguration(
    request: ReactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func reactivateConfiguration(withPolling: ReactivateConfigurationRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Configuration>
  {
    try await self.reactivateConfiguration(withPolling: withPolling, options: .init())
  }

  public func reactivateConfiguration(
    withPolling: ReactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Configuration>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func reactivateConfiguration(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Configuration> {
    let request = ReactivateConfigurationRequest().with {
      $0.name = name
    }
    return try await self.reactivateConfiguration(withPolling: request)
  }

  public func queryConfigurationLicenseUsage(request: QueryConfigurationLicenseUsageRequest)
    async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse
  {
    try await self.queryConfigurationLicenseUsage(request: request, options: .init())
  }

  public func queryConfigurationLicenseUsage(
    request: QueryConfigurationLicenseUsageRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func queryConfigurationLicenseUsage(
    name: Swift.String,
    startTime: GoogleCloudWKT.Timestamp?,
    endTime: GoogleCloudWKT.Timestamp?,
  ) async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse {
    let request = QueryConfigurationLicenseUsageRequest().with {
      $0.name = name
      $0.startTime = startTime
      $0.endTime = endTime
    }
    return try await self.queryConfigurationLicenseUsage(request: request)
  }

  public func aggregateUsage(request: AggregateUsageRequest) async throws
    -> GoogleCloudLicenseManagerV1.AggregateUsageResponse
  {
    try await self.aggregateUsage(request: request, options: .init())
  }

  public func aggregateUsage(
    request: AggregateUsageRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.AggregateUsageResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func aggregateUsage(
    byItem: AggregateUsageRequest
  ) throws -> any AsyncSequence<Usage, Swift.Error> {
    try self.aggregateUsage(byItem: byItem, options: .init())
  }

  public func aggregateUsage(
    byItem: AggregateUsageRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Usage, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLicenseManagerV1.AggregateUsageResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func aggregateUsage(
    name: Swift.String,
    startTime: GoogleCloudWKT.Timestamp?,
    endTime: GoogleCloudWKT.Timestamp?,
  ) throws -> any AsyncSequence<Usage, Swift.Error> {
    let request = AggregateUsageRequest().with {
      $0.name = name
      $0.startTime = startTime
      $0.endTime = endTime
    }
    return try self.aggregateUsage(byItem: request)
  }

  public func listProducts(request: ListProductsRequest) async throws
    -> GoogleCloudLicenseManagerV1.ListProductsResponse
  {
    try await self.listProducts(request: request, options: .init())
  }

  public func listProducts(
    request: ListProductsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListProductsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listProducts(
    byItem: ListProductsRequest
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    try self.listProducts(byItem: byItem, options: .init())
  }

  public func listProducts(
    byItem: ListProductsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLicenseManagerV1.ListProductsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listProducts(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Product, Swift.Error> {
    let request = ListProductsRequest().with {
      $0.parent = parent
    }
    return try self.listProducts(byItem: request)
  }

  public func getProduct(request: GetProductRequest) async throws
    -> GoogleCloudLicenseManagerV1.Product
  {
    try await self.getProduct(request: request, options: .init())
  }

  public func getProduct(
    request: GetProductRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Product {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getProduct(
    name: Swift.String,
  ) async throws -> GoogleCloudLicenseManagerV1.Product {
    let request = GetProductRequest().with {
      $0.name = name
    }
    return try await self.getProduct(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
