// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class LicenseManagerLogging: LicenseManagerStub {
    let inner: any LicenseManagerStub
    let logger: Logger

    public init(_ inner: any LicenseManagerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-licensemanager-v1"
      logger[metadataKey: "gcp.client.service"] = "licensemanager"
      logger[metadataKey: "gcp.experimental.swift.client"] = "LicenseManager"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listConfigurations(
      request: ListConfigurationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConfigurations",
        action: {
          (r: ListConfigurationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse
          in
          return try await self.inner.listConfigurations(request: r, options: o)
        })
    }

    public func getConfiguration(
      request: GetConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Configuration {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConfiguration",
        action: {
          (r: GetConfigurationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLicenseManagerV1.Configuration
          in
          return try await self.inner.getConfiguration(request: r, options: o)
        })
    }

    public func createConfiguration(
      request: CreateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createConfiguration",
        action: {
          (r: CreateConfigurationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.createConfiguration(request: r, options: o)
        })
    }

    public func updateConfiguration(
      request: UpdateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateConfiguration",
        action: {
          (r: UpdateConfigurationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.updateConfiguration(request: r, options: o)
        })
    }

    public func deleteConfiguration(
      request: DeleteConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteConfiguration",
        action: {
          (r: DeleteConfigurationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.deleteConfiguration(request: r, options: o)
        })
    }

    public func listInstances(
      request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListInstancesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listInstances",
        action: {
          (r: ListInstancesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLicenseManagerV1.ListInstancesResponse
          in
          return try await self.inner.listInstances(request: r, options: o)
        })
    }

    public func getInstance(
      request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Instance {
      try await self._intercept(
        request: request,
        options: options,
        name: "getInstance",
        action: {
          (r: GetInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLicenseManagerV1.Instance
          in
          return try await self.inner.getInstance(request: r, options: o)
        })
    }

    public func deactivateConfiguration(
      request: DeactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deactivateConfiguration",
        action: {
          (r: DeactivateConfigurationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.deactivateConfiguration(request: r, options: o)
        })
    }

    public func reactivateConfiguration(
      request: ReactivateConfigurationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "reactivateConfiguration",
        action: {
          (r: ReactivateConfigurationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.reactivateConfiguration(request: r, options: o)
        })
    }

    public func queryConfigurationLicenseUsage(
      request: QueryConfigurationLicenseUsageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "queryConfigurationLicenseUsage",
        action: {
          (r: QueryConfigurationLicenseUsageRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse
          in
          return try await self.inner.queryConfigurationLicenseUsage(request: r, options: o)
        })
    }

    public func aggregateUsage(
      request: AggregateUsageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.AggregateUsageResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "aggregateUsage",
        action: {
          (r: AggregateUsageRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLicenseManagerV1.AggregateUsageResponse
          in
          return try await self.inner.aggregateUsage(request: r, options: o)
        })
    }

    public func listProducts(
      request: ListProductsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListProductsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listProducts",
        action: {
          (r: ListProductsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLicenseManagerV1.ListProductsResponse
          in
          return try await self.inner.listProducts(request: r, options: o)
        })
    }

    public func getProduct(
      request: GetProductRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Product {
      try await self._intercept(
        request: request,
        options: options,
        name: "getProduct",
        action: {
          (r: GetProductRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLicenseManagerV1.Product
          in
          return try await self.inner.getProduct(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongrunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongrunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
